### ISSUE TITLE
C code for tree/XML exchange

### ISSUE THREAD

**Issue by swharden** [swharden/CJFLab#1]
Currently it's cumbersome to read/write tree objects from Python. C functions that convert to/from strings would be really convenient. When calling from python, it probably makes most sense to exchange data in a labtalk variables `pyTree` and `pyXML` . I'll omit the $ for the example.

```C
void xml_load_CJFGraph() {
// takes the tree object embedded in the graph window and puts it into labtalk "pyTree"
} 

void pyTreeToXML() {
// turns the labtalk "pyTree" into "pyXML"
// if an XML file intermediate is needed, make "pyXML" the XML file path
} 

tree pyXMLToTree() {
// turns the labtalk "pyXML" into "pyTree"
// if an XML file intermediate is needed, "pyXML" will be the XML file path
}
```

**Comment by cjfraz** [comment]
Ok... also done.  If python is great at XML to dict and back, then this may be a good solution. Let's talk about the python end for reading/changing values a little more.  For now...

GSToXML writes global settings from the ABFGraph in the active  folder to "c:\\apps\\pythonModules\\GSTemp.xml"

XMLToGS reads that xml file and writes it to the global settings of the ABFGraph in the active folder.

both functions (GSToXML, and XMLToGS) can be run from python using pyOrigin.LT_execute.

**Comment by swharden** [comment]
perfect! I finished the python end of XML file reading/parsing/modifying and stuck in as a module of SWHLab.

origin XML read/write code: https://github.com/swharden/SWHLab/commit/2439e4fa5490c94a31b511f5c27dd257156abf2e

**Comment by swharden** [comment]
I found extra functions in the code to do event detection tree conversion to XML and back

Currently alphabetized XML functions are:
* `GSToXML`
* `miniPToXML`
* `XMLtoMiniP`
* `XMLToGS`

Let's consider streamlining improving alphabetical organization by function and use:
* `XML_from_GS`
* `XML_from_MiniP`
* `XML_to_GS`
* `XML_to_MiniP`
