### ISSUE TITLE
automatically run labtalk command at end of python script execution

### ISSUE THREAD

**Issue by swharden** [swharden/CJFLab#2]
Please modify the `sc` function of `pyInterface.c` such that after the final LT_execute (which calls the python script), it checks for a labtalk string variable `pyLTafter` and if it exists, it runs its contents as labtalk code.

The reason this is required is because I need to execute python commands from from within labtalk scripts (i.e., `setpath; sc auto;`) to have progress bars, breaking ability, etc., and currently it won't allow execution of a python command from within a currently running python script.

**Comment by cjfraz** [comment]
I did this and it seems like a good enough solution for now. When we figure out the mechanism for more elegantly passing trees between python and OC (that allows for easy editing in python), let's come back and make this a node in the current pyVals tree. Right now we are cluttering up the Origin instance with session variables.

**Comment by swharden** [comment]
Looks good. `sc mt; sc addpaths;` works now, thanks!
code changes: https://github.com/swharden/SWHLab/commit/ab0be49ef2ca20b727e67d00e0580860345c0f6e
