### ISSUE TITLE
ABFGraph tree update idea

### ISSUE THREAD

**Issue by swharden** [swharden/CJFLab#4]
In python I now have a function to pull values from an old tree into a newer tree (with extra values the original tree didn't have), but I'm not sure how you want to call it with regard to origin projects. I want to use ABFBook as a holder of the XML. Do you think this will work? `setpath` wouldn't delete ABFData notes would it?

## proposed sequence ##
loop this on every ABFGraph of a project:
* `setpath wks` will select the worksheet
* `sc GSbackup` will:
  * `GSToXML` to put the (old format) XML into a file and python will read it
  * the ABFBook window will be automatically selected
  * `wksClearNote; wksAddNote(strXML);` will load the XML into the ABFBook note
* `setpath wks` will load the same ABF using the new tree structure
* `sc GSrestore` will pull values from the XML seen in the ABFBook note and update ABFGraph

**Comment by cjfraz** [comment]
proposed simpler workflow (for every ABFGraph in a project - but let's start with just one):
-LT_execute("GSToXML") to save global settings to XML.
-Read XML file into python XML class as GSOriginal.
-LT_execute('gs default') to load default settings from current version of C code into ABFGraph.
  (this will automatically add any new elements to the GUI that have been added in C since the ABFGraph was created).
-LT_execute("GSToXML") (again) to save new default parameters to XML file.
-Python function to read second XML file into second instance of the XML file class (say as GSNew).
-Python function to copy all values from GSOriginal to GSNew (ignore any value in GSNew that don't exist in GSOriginal, and ignore any values in GSOriginal that don't exist in GSNew).,
-Save updated GSNew to XML file on disk (same path and name as original).
-LT_execute("XMLToGS") to put updated tree back into ABFGraph.


?? 

I like this overall, but will need to make new 'gs default' that doesn't ever display the gui to the user (which will be easy).

**Comment by swharden** [comment]
Sounds good, I'll slightly modify the workflow, but I can work with this

* `GSToXML` to save old settings to XML.
* copy file
* Read XML file into python XML class as GSOriginal.
* `LT_execute('gs default')` to load default settings from current version of C code into ABFGraph.
  (this will automatically add any new elements to the GUI that have been added in C since the ABFGraph was created).
* `LT_execute("GSToXML")` (again) to overwrite new default parameters to XML file.
* Python function to read second XML file into second instance of the XML file class (say as GSNew).
* Python function to copy all values from GSOriginal to GSNew (ignore any value in GSNew that don't exist in GSOriginal, and ignore any values in GSOriginal that don't exist in GSNew).,
* Save updated GSNew to XML file on disk (same path and name as original).
* LT_execute("XMLToGS") to put updated tree back into ABFGraph.


?? 

I like this overall, but will need to make new 'gs default' that doesn't ever display the gui to the user (which will be easy).

**Comment by cjfraz** [comment]
Ok... so I modified 'gs' so now if you use run 'gs default 1' it will silently re-rewrite the global setting dialog in the ABFGraph with default values... meaning without ever showing the gui to the user and requiring them to click ok.  I think that was the only step necessary to enable the workflow above.

**Comment by swharden** [comment]
Excellent, I'm incorporating it right now. Note that I need to make a subtle change to GSToXML() but I can't edit CJF_pyInterface.c without risking having it deleted on the X-drive, so I'm copying the function into SWH.C, renaming it, and editing the new one.

The plan is for you to eventually cut/paste it from SWH.C back into the original C file. If we move toward github, it becomes a little easier.

**Comment by swharden** [comment]
I'm so close! But very stuck... I tried to make a highly versatile set of functions to save and load trees.
* `tree.Save(sFilename);` outputs a nearly blank XML document
* `out_tree(tree);` displays a really complete tree
any ideas?

recreate issue by:
`sc gain;
XML_tree_pull_gs("DEMO"); 
XML_tree_save("DEMO");`

XML_tree_save() is at: https://github.com/swharden/CJFLab/blob/master/SWH.C#L290

**Comment by swharden** [comment]
I resolved this issue. To save a tree from the project:
```c
TreeNode trGet; // GetTree requires a node, not a tree
Project.GetTree("PYVALS", trGet);	
Tree tree;
tree=trGet; // but you can copy a node into a tree
tree.Save("C:/Apps/pythonModules/XML.XML");
```

**Comment by cjfraz** [comment]
Yeah.. I was just starting to try something similar. Trees and treenodes are not exactly the same, but I’m not inclined to try and defend Origin on this one.   When you do Project.GetTree using an actual tree, it does work to the point that the data gets into C (and out_tree()) works… so bug seems specific to the save to XML method.

**Comment by swharden** [comment]
## Tree/XML exchange solution ##
I create a "tree/xml editor" as a tree object with two nodes (tree and xml) in the labtalk namespace which is easily available to python and labtalk. There are conversion routines to convert the tree to XML and vise versa. The C code I wrote to do all of this [has been added to SWH.C] (https://github.com/swharden/CJFLab/blame/master/SWH.C#L289)

I left the python out of this example. Therefore, you can't do fancy things (like key listing or direct editing) but search/replace works fine. An entirely C demo can be run by:
`sc mt; XML_from_gs(); XML_modify(); XML_to_gs(); memtest;`



## Today I learned
* just calling `anyTree.XML` returns a string containing the XML that composes it. 
* `anyTree.XML = strXMLstuff` directly modifies the tree.
* I suspect xml _already_ underlies all origin tree objects, which is why they are so easy to edit dynamically.
