### ISSUE TITLE
verbose setPath()

### ISSUE THREAD

**Issue by swharden** [swharden/CJFLab#5]
please add a verbose argument to setpath() which defaults to TRUE. If it is manually overridden all console output is suppressed. 

Please modify:
`void setPath(string strMode="OpenDialog", int iFileIndex=0)`

to be:
`void setPath(string strMode="OpenDialog", int iFileIndex=0, verbose=TRUE)`
... and according add if statements to control printing

**You can close this issue when it's complete. Thanks!**

**Comment by swharden** [comment]
... and same thing for `CJFMini`

`getstats` and `memtest` are already silent.

**Comment by cjfraz** [comment]
done for setpath... 
setpath wks 0 is slient.  (changed prototype so iFileIndex is last input param).

**Comment by swharden** [comment]
if I call it from labtalk and give it a path, it's not silent...
`setpath "X:\Data\2P01\2016\non-publish\2016-07-01 newprotos\16701003.abf" 0`

**Comment by cjfraz** [comment]
Whoops.  Fixed that case.

**Comment by cjfraz** [comment]
Doing too many things at once right now. Now fixed and also synced to the x drive.

**Comment by swharden** [comment]
Works great, thanks!
