### ISSUE TITLE
silent "gs default" needed

### ISSUE THREAD

**Issue by swharden** [swharden/CJFLab#6]
I have created the `sc GSupdate` command to:

* save old graph settings
* run `gs default` to update to the latest graph settings
* pulls each of the old settings into the new graph settings

Everything is seamless, except that running `gs default` requires the user to click OK every time. Can you add an argument to allow `gs default` to apply settings silently? Thanks.

**Comment by cjfraz** [comment]
Did that already.

Run ‘gs default 1’ for silent update.
